# Generated by Django 3.1 on 2020-08-18 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='alias',
        ),
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='FriendShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_student', to='mysite.student')),
                ('to_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_student', to='mysite.student')),
            ],
            options={
                'unique_together': {('from_student', 'to_student')},
            },
        ),
        migrations.AddField(
            model_name='student',
            name='friends',
            field=models.ManyToManyField(through='mysite.FriendShip', to='mysite.Student'),
        ),
    ]
